services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\Product\Application\:
        resource: '../../Application/*'
        exclude: '../../Domain/{Model}'

    Ergonode\Product\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{ValueObject}'

    Ergonode\Product\Infrastructure\:
        resource: '../../Infrastructure/*'
        exclude: '../../Infrastructure/{Message}'

    Ergonode\Product\Infrastructure\Persistence\:
        resource: '../../Infrastructure/Persistence/*'
        exclude: '../../Infrastructure/Persistence/{DataSet}'

    Ergonode\Product\Application\Controller\:
        resource: '../../Application/Controller'
        tags: ['controller.service_arguments']

    Ergonode\Product\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\Product\Infrastructure\Persistence\Projector\:
        resource: '../../Infrastructure/Persistence/Projector/*'
        tags: ['ergonode.event_sourcing.projector']

    Ergonode\Product\Infrastructure\Processor\BatchAction\:
        resource: '../../Infrastructure/Processor/BatchAction/*'
        tags: ['batch_action.processor_provider.interface']

    Ergonode\Product\Domain\Repository\ProductRepositoryInterface: '@Ergonode\Product\Infrastructure\Persistence\Repository\EventStoreProductRepository'

    Ergonode\Product\Application\Form\Product\BatchAction\:
        resource: '../../Application/Form/Product/BatchAction/*'

    Ergonode\Product\Domain\Query\ProductDashboardQueryInterface: '@Ergonode\Product\Infrastructure\Persistence\Query\DbalProductDashboardQuery'
    Ergonode\Product\Domain\Query\AttributeValueQueryInterface: '@Ergonode\Product\Infrastructure\Persistence\Query\DbalAttributeValueQuery'
    Ergonode\Product\Domain\Query\GetProductQueryInterface: '@Ergonode\Product\Infrastructure\Persistence\Query\GetProductQuery'
    Ergonode\Product\Domain\Query\ProductBindingQueryInterface: '@Ergonode\Product\Infrastructure\Persistence\Query\DbalProductBindingQuery'
    Ergonode\Product\Domain\Query\ProductCategoryGridQueryInterface: '@Ergonode\Product\Infrastructure\Persistence\Query\DbalProductCategoryGridQuery'
    Ergonode\Product\Domain\Query\ProductQueryInterface: '@Ergonode\Product\Infrastructure\Persistence\Query\DbalProductQuery'
    Ergonode\Product\Domain\Query\ProductHistoryGridQueryInterface: '@Ergonode\Product\Infrastructure\Persistence\Query\DbalProductHistoryGridQuery'
    Ergonode\Product\Domain\Query\ProductChildrenQueryInterface: '@Ergonode\Product\Infrastructure\Persistence\Query\DbalProductChildrenQuery'
    Ergonode\Product\Domain\Query\ProductChildrenGridQueryInterface: '@Ergonode\Product\Infrastructure\Persistence\Query\DbalProductChildrenGridQuery'
    Ergonode\Product\Domain\Query\ProductChildrenAvailableGridQueryInterface: '@Ergonode\Product\Infrastructure\Persistence\Query\DbalProductChildrenAvailableGridQuery'

    Ergonode\Product\Infrastructure\Persistence\Query\Decorator\CacheProductQueryDecorator:
        decorates: Ergonode\Product\Domain\Query\ProductQueryInterface
        arguments:
            - '@Ergonode\Product\Infrastructure\Persistence\Query\Decorator\CacheProductQueryDecorator.inner'

    Ergonode\Product\Infrastructure\Provider\ProductStrategyProvider:
        arguments:
            $productStrategies: !tagged_iterator 'component.product.product_factory_strategy'
