services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\Product\Application\:
        resource: '../../Application/*'
        exclude: '../../Domain/{Model}'

    Ergonode\Product\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{ValueObject}'

    Ergonode\Product\Infrastructure\:
        resource: '../../Infrastructure/*'
        exclude: '../../Infrastructure/{Message}'

    Ergonode\Product\Application\Controller\:
        resource: '../../Application/Controller'
        tags: ['controller.service_arguments']

    Ergonode\Product\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\Product\Infrastructure\Persistence\Projector\:
        resource: '../../Infrastructure/Persistence/Projector/*'
        tags: ['messenger.message_handler']

    Ergonode\Product\Infrastructure\JMS\Serializer\Handler\:
        resource: '../../Infrastructure/JMS/Serializer/Handler/*'
        tags: ['jms_serializer.subscribing_handler']

    Ergonode\Product\Infrastructure\Processor\BatchAction\:
        resource: '../../Infrastructure/Processor/BatchAction/*'
        tags: ['batch_action.processor_provider.interface']

    Ergonode\Product\Domain\Repository\ProductRepositoryInterface: '@Ergonode\Product\Infrastructure\Persistence\Repository\DbalProductRepository'
    Ergonode\Product\Domain\Query\ProductQueryInterface: '@Ergonode\Product\Infrastructure\Persistence\Query\DbalProductQuery'
    Ergonode\Product\Domain\Query\HistoryQueryInterface: '@Ergonode\Product\Infrastructure\Persistence\Query\DbalHistoryQuery'
    Ergonode\Product\Domain\Query\GetProductQueryInterface: '@Ergonode\Product\Infrastructure\Persistence\Query\GetProductQuery'

    Ergonode\Product\Infrastructure\Persistence\Query\Decorator\CacheProductQueryDecorator:
        decorates: Ergonode\Product\Domain\Query\ProductQueryInterface
        arguments:
            - '@Ergonode\Product\Infrastructure\Persistence\Query\Decorator\CacheProductQueryDecorator.inner'
