services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\Core\Persistence\:
        resource: '../../Persistence/*'

    Ergonode\Core\Application\:
        resource: '../../Application/*'

    Ergonode\Core\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{Entity, ValueObject}'

    Ergonode\Core\Application\Controller\:
        resource: '../../Application/Controller'
        tags: ['controller.service_arguments']

    Ergonode\Core\Infrastructure\:
        resource: '../../Infrastructure/*'

    Ergonode\Core\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\Core\Persistence\Dbal\Projector\:
        resource: '../../Persistence/Dbal/Projector/*'
        tags: ['messenger.message_handler']

    Ergonode\Core\Infrastructure\JMS\Serializer\Handler\:
        resource: '../../Infrastructure/JMS/Serializer/Handler/*'
        tags: ['jms_serializer.subscribing_handler']

    Ergonode\Core\Application\Provider\SimpleDirectoryProvider:
        arguments:
            $directory: '%kernel.project_dir%'

    Ergonode\Core\Application\Form\Extension\:
        resource: '../../Application/Form/Extension/*'
        tags: ['liform.extension']

    Ergonode\Core\Domain\Query\LanguageQueryInterface: '@Ergonode\Core\Persistence\Dbal\Query\DbalLanguageQuery'
    Ergonode\Core\Domain\Query\UnitQueryInterface: '@Ergonode\Core\Persistence\Dbal\Query\DbalUnitQuery'
    Ergonode\Core\Domain\Repository\LanguageRepositoryInterface: '@Ergonode\Core\Persistence\Dbal\Repository\DbalLanguageRepository'
    Ergonode\Core\Domain\Repository\UnitRepositoryInterface: '@Ergonode\Core\Persistence\Dbal\Repository\DbalUnitRepository'
    Ergonode\Core\Application\Provider\DirectoryProviderInterface: '@Ergonode\Core\Application\Provider\SimpleDirectoryProvider'
    Ergonode\Core\Infrastructure\Resolver\RelationshipsResolverInterface: '@Ergonode\Core\Infrastructure\Resolver\RelationshipsResolver'

    Ergonode\Core\Infrastructure\JMS\Serializer\HandlerRegistry:
        decorates: 'jms_serializer.handler_registry'
        arguments:
            $handlers: !tagged 'jms_serializer.subscribing_handler'
            $registry: '@Ergonode\Core\Infrastructure\JMS\Serializer\HandlerRegistry.inner'

    # overriding message serializer
    messenger.transport.serializer:
        class: 'Ergonode\Core\Infrastructure\Transport\Serializer\TransportMessageSerializer'
