services:
    _defaults:
            autowire: true
            autoconfigure: true
            public: false

    Ergonode\Generator\Generator\:
        resource: '../../Generator/*'

    Ergonode\Generator\Builder\:
        resource: '../../Builder/*'

    Ergonode\Generator\Persister\FilePersister:
        arguments:
            $directory: '%kernel.root_dir%/../'

    Ergonode\Generator\Generator\EntityGenerator:
        arguments:
            - '@Ergonode\Generator\Persister\FilePersister'
            - '@Ergonode\Generator\Builder\Domain\Entity\EntityClassBuilder'
            - '@Ergonode\Generator\Builder\Domain\Entity\EntityIdClassBuilder'
            - '@Ergonode\Generator\Builder\Domain\Repository\EntityRepositoryInterfaceBuilder'
            - '@Ergonode\Generator\Builder\Persistence\Dbal\Repository\EntityDbalRepositoryBuilder'
            - '@Ergonode\Generator\Builder\Domain\Factory\EntityFactoryInterfaceBuilder'
            - '@Ergonode\Generator\Builder\Domain\Factory\EntityFactoryBuilder'
            - '@Ergonode\Generator\Builder\Domain\Command\CreateCommandClassBuilder'
            - '@Ergonode\Generator\Builder\Domain\Event\CreateEventBuilder'
            - '@Ergonode\Generator\Builder\Infrastructure\Handler\CreateCommandHandlerClassBuilder'

    Ergonode\Generator\Command\:
        resource: '../../Command/*'
        tags: ['console.command']

