# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'
        export.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/export'
        multimedia.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/multimedia'
        avatar.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/avatar'
