security:
    access_decision_manager:
        strategy: 'unanimous'
        allow_if_all_abstain: false

    providers:
        email_user_provider:
            id: 'Ergonode\Authentication\Application\Security\Provider\EmailUserProvider'
        id_user_provider:
            id: 'Ergonode\Authentication\Application\Security\Provider\IdUserProvider'

    encoders:
        Ergonode\Account\Domain\Entity\User:
            algorithm: 'bcrypt'
        Ergonode\Authentication\Application\Security\User\User:
            algorithm: 'bcrypt'

    firewalls:
        dev:
            pattern: '^/(_(profiler|wdt)|css|images|js)/'
            security: false
        doc:
            pattern: '^/$|^/api/doc'
            security: false
        login:
            pattern:  '^/api/v1/login$'
            stateless: true
            user_checker: 'Ergonode\Account\Application\Security\Checker\UserActivityChecker'
            provider: 'email_user_provider'
            json_login:
                check_path: /api/v1/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        refresh:
            pattern: '^/api/v1/token/refresh'
            stateless: true
            anonymous: true
        reset:
            pattern: '^/api/v1/accounts/token'
            stateless: true
            anonymous: true
        api:
            pattern: '^/api'
            stateless: true
            security: true
            guard:
                provider: 'id_user_provider'
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        base:
            pattern: '^/'
            security: true
            anonymous: ~
            entry_point: ~

    access_control:
        - { path: '^/api/v1/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/api/v1/token/refresh', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/api/v1/accounts/token', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/api', roles: IS_AUTHENTICATED_FULLY }
