services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\Multimedia\Application\:
        resource: '../../Application/*'

    Ergonode\Multimedia\Infrastructure\:
        resource: '../../Infrastructure/*'
        exclude: '../../Infrastructure/{Message}'

    Ergonode\Multimedia\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{Entity,ValueObject}'

    Ergonode\Multimedia\Application\Controller\:
        resource: '../../Application/Controller/*'
        tags: ['controller.service_arguments']

    Ergonode\Multimedia\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\Multimedia\Infrastructure\Persistence\Projector\:
        resource: '../../Infrastructure/Persistence/Projector/*'
        tags: ['ergonode.event_sourcing.projector']

    Ergonode\Multimedia\Domain\Query\MultimediaQueryInterface: '@Ergonode\Multimedia\Infrastructure\Persistence\Query\DbalMultimediaQuery'
    Ergonode\Multimedia\Domain\Query\MultimediaGridQueryInterface: '@Ergonode\Multimedia\Infrastructure\Persistence\Query\DbalMultimediaGridQuery'
    Ergonode\Multimedia\Domain\Repository\MultimediaRepositoryInterface: '@Ergonode\Multimedia\Infrastructure\Persistence\Repository\EventStoreMultimediaRepository'
    Ergonode\Multimedia\Infrastructure\Service\HashCalculationServiceInterface: '@Ergonode\Multimedia\Infrastructure\Service\SHACalculationService'

    Ergonode\Multimedia\Infrastructure\Service\Thumbnail\ThumbnailGenerationStrategyProvider:
        arguments:
            - '@Ergonode\Multimedia\Infrastructure\Service\Thumbnail\Strategy\DefaultThumbnailGenerationStrategy'
