services:
    _defaults:
            autowire: true
            autoconfigure: true
            public: false

    Ergonode\Multimedia\Application\:
        resource: '../../Application/*'

    Ergonode\Multimedia\Persistence\:
        resource: '../../Persistence/*'

    Ergonode\Multimedia\Infrastructure\:
        resource: '../../Infrastructure/*'
        exclude: '../../Infrastructure/{Message}'

    Ergonode\Multimedia\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{Entity,ValueObject}'

    Ergonode\Multimedia\Application\Controller\:
        resource: '../../Application/Controller/*'
        tags: ['controller.service_arguments']

    Ergonode\Multimedia\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\Multimedia\Persistence\Dbal\Projector\:
        resource: '../../Persistence/Dbal/Projector/*'
        tags: ['messenger.message_handler']

    Ergonode\Multimedia\Infrastructure\JMS\Serializer\Handler\:
        resource: '../../Infrastructure/JMS/Serializer/Handler/*'
        tags: ['jms_serializer.subscribing_handler']

    Ergonode\Multimedia\Domain\Query\MultimediaQueryInterface: '@Ergonode\Multimedia\Persistence\Dbal\Query\DbalMultimediaQuery'
    Ergonode\Multimedia\Domain\Repository\MultimediaRepositoryInterface: '@Ergonode\Multimedia\Persistence\Dbal\Repository\DbalMultimediaRepository'
    Ergonode\Multimedia\Infrastructure\Service\HashCalculationServiceInterface: '@Ergonode\Multimedia\Infrastructure\Service\SHACalculationService'

    Ergonode\Multimedia\Infrastructure\Service\Thumbnail\ThumbnailGenerationStrategyProvider:
        arguments:
            - '@Ergonode\Multimedia\Infrastructure\Service\Thumbnail\Strategy\DefaultThumbnailGenerationStrategy'