language: php
php:
  - 7.4

install:
  - composer install

services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
before_script:
  - psql -c "CREATE ROLE ergonode LOGIN  PASSWORD '123' CREATEDB" -U postgres
  - psql -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";' -U postgres --dbname template1
  - psql -c 'CREATE EXTENSION IF NOT EXISTS "ltree";' -U postgres --dbname template1
  - psql -c 'CREATE DATABASE ergonode_test OWNER ergonode' -U postgres
  - openssl genrsa -aes256 -passout pass:1234 -out "config/jwt/private.pem" 4096
  - openssl rsa -pubout -in "config/jwt/private.pem"  -passin pass:1234 -out "config/jwt/public.pem"
env:
  global:
    - APP_ENV=test
    - DATABASE_URL="pgsql://ergonode:123@localhost:5432/ergonode_test?serverVersion=10&charset=utf8"
script:
  - php bin/phing check:style
  - php bin/phing test:unit
  - export DATABASE_URL="pgsql://ergonode:123@localhost:5432/ergonode_test?serverVersion=10&charset=utf8"
  - php bin/phing test:behat