services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\ExporterShopware6\Application\:
        resource: '../../Application/*'

    Ergonode\ExporterShopware6\Domain\:
        resource: '../../Domain/*'

    Ergonode\ExporterShopware6\Infrastructure\:
        resource: '../../Infrastructure/*'
        exclude: ['../../Infrastructure/{Model}', '../../Infrastructure/Connector/{Action}']

    Ergonode\ExporterShopware6\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\ExporterShopware6\Infrastructure\Connector\Shopware6Connector:
        $logger: '@monolog.logger.channel'

    Ergonode\ExporterShopware6\Infrastructure\Handler\ProcessExportCommandHandler:
        tags: ['messenger.message_handler']
        arguments:
            $steps:
                - '@Ergonode\ExporterShopware6\Infrastructure\Processor\Step\PropertyGroupStep'
                - '@Ergonode\ExporterShopware6\Infrastructure\Processor\Step\CustomFieldStep'
                - '@Ergonode\ExporterShopware6\Infrastructure\Processor\Step\CategoryStep'
                - '@Ergonode\ExporterShopware6\Infrastructure\Processor\Step\VariableProductStep'
                - '@Ergonode\ExporterShopware6\Infrastructure\Processor\Step\SimpleProductStep'
                - '@Ergonode\ExporterShopware6\Infrastructure\Processor\Step\CategoryRemoveStep'
                - '@Ergonode\ExporterShopware6\Infrastructure\Processor\Step\ProductCrossSellingStep'
    # Repository
    Ergonode\ExporterShopware6\Domain\Repository\CategoryRepositoryInterface: '@Ergonode\ExporterShopware6\Infrastructure\Persistence\Repository\DbalCategoryRepository'
    Ergonode\ExporterShopware6\Domain\Repository\CurrencyRepositoryInterface: '@Ergonode\ExporterShopware6\Infrastructure\Persistence\Repository\DbalCurrencyRepository'
    Ergonode\ExporterShopware6\Domain\Repository\TaxRepositoryInterface: '@Ergonode\ExporterShopware6\Infrastructure\Persistence\Repository\DbalTaxRepository'
    Ergonode\ExporterShopware6\Domain\Repository\PropertyGroupRepositoryInterface: '@Ergonode\ExporterShopware6\Infrastructure\Persistence\Repository\DbalPropertyGroupRepository'
    Ergonode\ExporterShopware6\Domain\Repository\CustomFieldRepositoryInterface: '@Ergonode\ExporterShopware6\Infrastructure\Persistence\Repository\DbalCustomFieldRepository'
    Ergonode\ExporterShopware6\Domain\Repository\ProductRepositoryInterface: '@Ergonode\ExporterShopware6\Infrastructure\Persistence\Repository\DbalProductRepository'
    Ergonode\ExporterShopware6\Domain\Repository\ProductCrossSellingRepositoryInterface: '@Ergonode\ExporterShopware6\Infrastructure\Persistence\Repository\DbalProductCrossSellingRepository'
    Ergonode\ExporterShopware6\Domain\Repository\LanguageRepositoryInterface: '@Ergonode\ExporterShopware6\Infrastructure\Persistence\Repository\DbalLanguageRepository'
    Ergonode\ExporterShopware6\Domain\Repository\MultimediaRepositoryInterface: '@Ergonode\ExporterShopware6\Infrastructure\Persistence\Repository\DbalMultimediaRepository'
    Ergonode\ExporterShopware6\Domain\Repository\PropertyGroupOptionsRepositoryInterface: '@Ergonode\ExporterShopware6\Infrastructure\Persistence\Repository\DbalPropertyGroupOptionsRepository'


    # Query
    Ergonode\ExporterShopware6\Domain\Query\CategoryQueryInterface: '@Ergonode\ExporterShopware6\Infrastructure\Persistence\Query\DbalCategoryQuery'
    Ergonode\ExporterShopware6\Domain\Query\PropertyGroupQueryInterface: '@Ergonode\ExporterShopware6\Infrastructure\Persistence\Query\DbalPropertyGroupQuery'
    Ergonode\ExporterShopware6\Domain\Query\CustomFieldQueryInterface: '@Ergonode\ExporterShopware6\Infrastructure\Persistence\Query\DbalCustomFiledQuery'
    Ergonode\ExporterShopware6\Domain\Query\CurrencyQueryInterface: '@Ergonode\ExporterShopware6\Infrastructure\Persistence\Query\DbalCurrencyQuery'
    Ergonode\ExporterShopware6\Domain\Query\LanguageQueryInterface: '@Ergonode\ExporterShopware6\Infrastructure\Persistence\Query\DbalLanguageQuery'
    Ergonode\ExporterShopware6\Domain\Query\MultimediaQueryInterface: '@Ergonode\ExporterShopware6\Infrastructure\Persistence\Query\DbalMultimediaQuery'
    Ergonode\ExporterShopware6\Domain\Query\TaxQueryInterface: '@Ergonode\ExporterShopware6\Infrastructure\Persistence\Query\DbalTaxQuery'
    Ergonode\ExporterShopware6\Domain\Query\ProductCrossSellingQueryInterface: '@Ergonode\ExporterShopware6\Infrastructure\Persistence\Query\DbalProductCrossSellingQuery'

    # Synchronizer
    Ergonode\ExporterShopware6\Infrastructure\Processor\Process\StartShopware6ExportProcess:
        arguments:
            - '@Ergonode\ExporterShopware6\Infrastructure\Synchronizer\CurrencySynchronizer'
            - '@Ergonode\ExporterShopware6\Infrastructure\Synchronizer\TaxSynchronizer'
            - '@Ergonode\ExporterShopware6\Infrastructure\Synchronizer\LanguageSynchronizer'

    # Mappers
    Ergonode\ExporterShopware6\Infrastructure\Builder\PropertyGroupBuilder:
        arguments:
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\PropertyGroup\PropertyGroupNameMapper'

    Ergonode\ExporterShopware6\Infrastructure\Builder\PropertyGroupOptionBuilder:
        arguments:
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\PropertyGroupOption\PropertyGroupOptionNameMapper'

    Ergonode\ExporterShopware6\Infrastructure\Builder\CustomFieldBuilder:
        arguments:
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\CustomField\CustomFieldNameMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\CustomField\CustomFieldLabelMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\CustomField\CustomFieldConfigTextMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\CustomField\CustomFieldConfigTextareaMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\CustomField\CustomFieldConfigDateMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\CustomField\CustomFieldConfigMediaMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\CustomField\CustomFieldConfigNumericMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\CustomField\CustomFieldConfigSelectMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\CustomField\CustomFieldConfigMultiSelectMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\CustomField\CustomFieldConfigOptionsMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\CustomField\CustomFieldConfigUnitMapper'

    Ergonode\ExporterShopware6\Infrastructure\Builder\CategoryBuilder:
        arguments:
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Category\CategoryNameMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Category\CategoryParentMapper'

    Ergonode\ExporterShopware6\Infrastructure\Builder\ProductBuilder:
        arguments:
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\ProductSkuMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\ProductNameMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\Decorator\NewProductPriceMapperDecorator'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\ProductCategoryMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\ProductActiveMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\Decorator\NewProductStockMapperDecorator'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\ProductDescriptionMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\ProductGalleryMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\PropertyGroup\ProductGroupSelectMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\PropertyGroup\ProductGroupMultiSelectMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\CustomField\ProductCustomFieldSetTextMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\CustomField\ProductCustomFieldSetTextAreaMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\CustomField\ProductCustomFieldSetNumericMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\CustomField\ProductCustomFieldSetDateTimeMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\CustomField\ProductCustomFieldSetSelectMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\CustomField\ProductCustomFieldSetMultiSelectMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\CustomField\ProductCustomFieldSetMultimediaMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\CustomField\ProductCustomFieldSetUnitMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\ProductVariantMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\ProductVariantChildMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\ProductCoverMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\ProductSEOMetaTitleMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\ProductSEOMetaDescriptionMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\Product\ProductSEOKeywordsMapper'

    Ergonode\ExporterShopware6\Infrastructure\Builder\ProductCrossSellingBuilder:
        arguments:
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\ProductCrossSelling\ProductCrossSellingRootProductIdMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\ProductCrossSelling\ProductCrossSellingNameMapper'
            - '@Ergonode\ExporterShopware6\Infrastructure\Mapper\ProductCrossSelling\ProductCrossSellingChildrenMapper'
