services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\ImporterErgonode1\Application\:
        resource: '../../Application/*'

    Ergonode\ImporterErgonode1\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{Entity}'

    Ergonode\ImporterErgonode1\Infrastructure\:
        resource: '../../Infrastructure/*'

    Ergonode\ImporterErgonode1\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\ImporterErgonode1\Infrastructure\Resolver\ProductCommandResolver:
        arguments:
            - !tagged_iterator 'component.ergonode-importer.product_command_factory_interface'

    Ergonode\ImporterErgonode1\Infrastructure\Resolver\AttributeCommandResolver:
        arguments:
            - !tagged_iterator 'component.ergonode-importer.attribute_command_factory'

    Ergonode\ImporterErgonode1\Infrastructure\Processor\ErgonodeImportProcess:
        arguments:
            $steps:
                - '@Ergonode\ImporterErgonode1\Infrastructure\Processor\Step\ErgonodeAttributesProcessorStep'
                - '@Ergonode\ImporterErgonode1\Infrastructure\Processor\Step\ErgonodeOptionsProcessorStep'
                - '@Ergonode\ImporterErgonode1\Infrastructure\Processor\Step\ErgonodeCategoriesProcessorStep'
                - '@Ergonode\ImporterErgonode1\Infrastructure\Processor\Step\ErgonodeTemplateProcessorStep'
                - '@Ergonode\ImporterErgonode1\Infrastructure\Processor\Step\ErgonodeSimpleProductProcessorStep'
                - '@Ergonode\ImporterErgonode1\Infrastructure\Processor\Step\ErgonodeGroupingProductProcessorStep'
                - '@Ergonode\ImporterErgonode1\Infrastructure\Processor\Step\ErgonodeVariableProductProcessorStep'
