nelmio_api_doc:
    documentation:
        attribute_definitions:
            option:
                type: object
                properties:
                    key:
                        type: string
                        required: true
                        description: option key
                        example: key_1
                    value:
                        $ref: "#/definitions/translation"
                example:
                    code: key_1
                    label:
                        pl_PL: Option PL 1
                        en_GB: Option EN 1
            attribute_group:
                type: object
                properties:
                    code:
                        type: string
                        required: true
                        description: attribute group code
                    name:
                        type: string
                        required: true
                        description: attribute group name
                example:
                    code: 'attribute_group_code'
                    name:
                        pl_PL: 'Nazwa grupy PL'
                        en_GB: 'Name of group EN'
            attribute_group_update:
                type: object
                properties:
                    name:
                        type: string
                        required: true
                        description: attribute group name
                example:
                    name:
                        pl_PL: 'Nazwa grupy PL'
                        en_GB: 'Name of group EN'
            attribute:
                type: object
                properties:
                    code:
                        type: string
                        required: true
                        description: attribute code
                        example: attribute_code_1
                    type:
                        type: string
                        required: true
                        description: attribute type
                        example: SELECT
                    label:
                        $ref: "#/definitions/translation"
                    hint:
                        $ref: "#/definitions/translation"
                    placeholder:
                        $ref: "#/definitions/translation"
                    groups:
                        type: array
                        required: true
                        items:
                            type: string
                        example:
                            - 9b0ceb29-26ac-4852-a602-6e5680a3a029
                    multilingual:
                        type: boolean
                        required: true
                        example: true
                    parameters:
                        $ref: "#/definitions/attribute_parameters"
            attribute_parameters:
                type: object
                properties:
                    format:
                        type: string
                        required: false
                        description: Additional format information (If used by attribute)
                        example: YYYY-MM-DDDD

