services:
    _defaults:
            autowire: true
            autoconfigure: true
            public: false

    Ergonode\Transformer\Persistence\:
        resource: '../../Persistence/*'

    Ergonode\Transformer\Application\:
        resource: '../../Application/*'

    Ergonode\Transformer\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{Entity, ValueObject, Model}'

    Ergonode\Transformer\Infrastructure\:
        resource: '../../Infrastructure/*'
        exclude: '../../Infrastructure/{Message}'

    Ergonode\Transformer\Application\Controller\:
        resource: '../../Application/Controller'
        tags: ['controller.service_arguments']

    Ergonode\Transformer\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\Transformer\Infrastructure\JMS\Serializer\Handler\:
        resource: '../../Infrastructure/JMS/Serializer/Handler/*'
        tags: ['jms_serializer.subscribing_handler']

    Ergonode\Transformer\Infrastructure\JMS\Serializer\Handler\ConverterInterfaceHandler:
        calls:
            - ['set', ['Ergonode\Transformer\Infrastructure\Converter\TextConverter']]
            - ['set', ['Ergonode\Transformer\Infrastructure\Converter\TranslationConverter']]
            - ['set', ['Ergonode\Transformer\Infrastructure\Converter\SlugConverter']]
            - ['set', ['Ergonode\Transformer\Infrastructure\Converter\JoinConverter']]
            - ['set', ['Ergonode\Transformer\Infrastructure\Converter\DateConverter']]
            - ['set', ['Ergonode\Transformer\Infrastructure\Converter\ConstConverter']]
            - ['set', ['Ergonode\Transformer\Infrastructure\Converter\MappingConverter']]
            - ['set', ['Ergonode\Transformer\Infrastructure\Converter\CollectionConverter']]
            - ['set', ['Ergonode\Transformer\Infrastructure\Converter\SplitConverter']]

    Ergonode\Transformer\Domain\Repository\TransformerRepositoryInterface: '@Ergonode\Transformer\Persistence\Dbal\Repository\DbalTransformerRepository'
    Ergonode\Transformer\Domain\Repository\ProcessorRepositoryInterface: '@Ergonode\Transformer\Persistence\Dbal\Repository\DbalProcessorRepository'
    Ergonode\Transformer\Domain\Query\ProcessorQueryInterface: '@Ergonode\Transformer\Persistence\Dbal\Query\DbalProcessorQuery'
