parameters:
    import_directory: '%kernel.project_dir%/import/'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\Importer\Application\:
        resource: '../../Application/*'

#    Ergonode\Importer\Application\Command\:
#        resource: '../../Application/Command/*'
#        tags: ['console.command']

    Ergonode\Importer\Application\Controller\Api\:
        resource: '../../Application/Controller/Api/*'
        tags: ['controller.service_arguments']

    Ergonode\Importer\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{Entity,ValueObject}'

    Ergonode\Importer\Infrastructure\:
        resource: '../../Infrastructure/*'

    Ergonode\Importer\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\Importer\Infrastructure\JMS\Serializer\Handler\:
        resource: '../../Infrastructure/JMS/Serializer/Handler/*'
        tags: ['jms_serializer.subscribing_handler']

    Ergonode\Importer\Domain\Repository\ImportRepositoryInterface: '@Ergonode\Importer\Infrastructure\Persistence\Repository\DbalImportRepository'
    Ergonode\Importer\Domain\Query\ImportQueryInterface: '@Ergonode\Importer\Infrastructure\Persistence\Query\DbalImportQuery'

    Ergonode\Importer\Application\Service\Upload\UploadService:
        arguments:
            $targetDirectory: '%import_directory%'

    Ergonode\Importer\Infrastructure\Provider\AttributeProposalProvider:
        arguments:
            - '@Ergonode\Importer\Infrastructure\Proposal\Strategy\TextAreaProposalStrategy'
            - '@Ergonode\Importer\Infrastructure\Proposal\Strategy\NumericProposalStrategy'
            - '@Ergonode\Importer\Infrastructure\Proposal\Strategy\MultiSelectProposalStrategy'
            - '@Ergonode\Importer\Infrastructure\Proposal\Strategy\TextProposalStrategy'