services:
    _defaults:
            autowire: true
            autoconfigure: true
            public: false

    Ergonode\Editor\Application\:
        resource: '../../Application/*'

    Ergonode\Editor\Persistence\:
        resource: '../../Persistence/*'

    Ergonode\Editor\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{Entity, ValueObject}'

    Ergonode\Editor\Infrastructure\:
        resource: '../../Infrastructure/*'
        exclude: '../../Infrastructure/{Message}'

    Ergonode\Editor\Application\Controller\:
        resource: '../../Application/Controller/*'
        tags: ['controller.service_arguments']

    Ergonode\Editor\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\Editor\Infrastructure\JMS\Serializer\Handler\:
        resource: '../../Infrastructure/JMS/Serializer/Handler/*'
        tags: ['jms_serializer.subscribing_handler']

    Ergonode\Editor\Domain\Repository\ProductDraftRepositoryInterface: '@Ergonode\Editor\Persistence\Repository\DbalProductDraftRepository'
    Ergonode\Editor\Domain\Query\DraftQueryInterface: '@Ergonode\Editor\Persistence\Query\DbalDraftQuery'
