services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\Channel\Application\:
        resource: '../../Application/*'

    Ergonode\Channel\Application\Controller\Api\:
        resource: '../../Application/Controller/Api/*'
        tags: ['controller.service_arguments']

    Ergonode\Channel\Application\Command\:
        resource: '../../Application/Command/*'
        tags: ['console.command']

    Ergonode\Channel\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{ValueObject}'

    Ergonode\Channel\Infrastructure\:
        resource: '../../Infrastructure/*'

    Ergonode\Channel\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\Channel\Infrastructure\Handler\Export\DeleteExportCommandHandler:
        tags: [ { name: 'messenger.message_handler', priority: -10 } ]

    Ergonode\Channel\Domain\Repository\SchedulerRepositoryInterface: '@Ergonode\Channel\Infrastructure\Persistence\Repository\DbalSchedulerRepository'
    Ergonode\Channel\Domain\Repository\ChannelRepositoryInterface: '@Ergonode\Channel\Infrastructure\Persistence\Repository\DbalChannelRepository'
    Ergonode\Channel\Domain\Query\ChannelGridQueryInterface: '@Ergonode\Channel\Infrastructure\Persistence\Query\DbalChannelGridQuery'
    Ergonode\Channel\Domain\Query\ChannelQueryInterface: '@Ergonode\Channel\Infrastructure\Persistence\Query\DbalChannelQuery'
    Ergonode\Channel\Domain\Query\ExportQueryInterface: '@Ergonode\Channel\Infrastructure\Persistence\Query\DbalExportQuery'
    Ergonode\Channel\Domain\Query\ExportGridQueryInterface: '@Ergonode\Channel\Infrastructure\Persistence\Query\DbalExportGridQuery'
    Ergonode\Channel\Domain\Query\ExportErrorGridQueryInterface: '@Ergonode\Channel\Infrastructure\Persistence\Query\DbalExportErrorGridQuery'
