services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\Workflow\Application\:
        resource: '../../Application/*'
        exclude: '../../Domain/{Model}'

    Ergonode\Workflow\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{Entity, ValueObject, Event}'

    Ergonode\Workflow\Infrastructure\:
        resource: '../../Infrastructure/*'
        exclude: '../../Infrastructure/{Message}'

    Ergonode\Workflow\Application\Controller\:
        resource: '../../Application/Controller'
        tags: ['controller.service_arguments']

    Ergonode\Workflow\Infrastructure\Handler\:
        resource: '../../Infrastructure/Handler/*'
        tags: ['messenger.message_handler']

    Ergonode\Workflow\Infrastructure\Persistence\Projector\:
        resource: '../../Infrastructure/Persistence/Projector/*'
        tags: ['messenger.message_handler']

    Ergonode\Workflow\Infrastructure\JMS\Serializer\Handler\:
        resource: '../../Infrastructure/JMS/Serializer/Handler/*'
        tags: ['jms_serializer.subscribing_handler']

    Ergonode\Workflow\Domain\Repository\StatusRepositoryInterface: '@Ergonode\Workflow\Infrastructure\Persistence\Repository\DbalStatusRepository'
    Ergonode\Workflow\Domain\Repository\WorkflowRepositoryInterface: '@Ergonode\Workflow\Infrastructure\Persistence\Repository\DbalWorkflowRepository'
    Ergonode\Workflow\Domain\Query\StatusQueryInterface: '@Ergonode\Workflow\Infrastructure\Persistence\Query\DbalStatusQuery'
    Ergonode\Workflow\Domain\Query\TransitionQueryInterface: '@Ergonode\Workflow\Infrastructure\Persistence\Query\DbalTransitionQuery'
    Ergonode\Workflow\Domain\Query\WorkflowQueryInterface: '@Ergonode\Workflow\Infrastructure\Persistence\Query\DbalWorkflowQuery'

    Ergonode\Workflow\Application\Request\ParamConverter\AbstractWorkflowParamConverter:
        class: Ergonode\Workflow\Application\Request\ParamConverter\AbstractWorkflowParamConverter
        tags:
            - { name: request.param_converter, priority: 2, converter: abstract_workflow_param_converter }
